const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const {createServer,MAX_BODY,MAX_UPSTREAM,staticFile,loopbackUrl,inferencePayload}=require('../server');
const server=options=>createServer({...options,csrfToken:'test'});
async function request(instance,method,url,body,headers={}){await new Promise(r=>instance.listen(0,'127.0.0.1',r));const port=instance.address().port;return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,method,path:url,headers:{'content-type':'application/json','x-csrf-token':'test',origin:`http://127.0.0.1:${port}`,...headers}},res=>{let data='';res.on('data',c=>data+=c);res.on('end',()=>{instance.close();resolve({status:res.statusCode,body:data,headers:res.headers});});});req.on('error',reject);req.end(body);});}
test('serves panel with Zoom frame policy and HSTS',async()=>{const result=await request(server(),'GET','/');assert.equal(result.status,200);assert.match(result.headers['content-security-policy'],/https:\/\/zoom\.us https:\/\/\*\.zoom\.us/);assert.match(result.headers['strict-transport-security'],/max-age/);});
test('requires same-origin CSRF token',async()=>{assert.equal((await request(server(),'POST','/api/interpret','{}',{'x-csrf-token':'wrong'})).status,403);});
test('rejects invalid input, oversized bodies, and traversal',async()=>{assert.equal((await request(server(),'POST','/api/interpret','{}')).status,400);const large=JSON.stringify({image:'data:image/jpeg;base64,'+'A'.repeat(MAX_BODY)});assert.equal((await request(server(),'POST','/api/interpret',large)).status,413);assert.equal((await request(server(),'GET','/%2e%2e/server.js')).status,404);assert.equal(staticFile('/../server.js'),null);});
test('proxies only bounded valid schema',async()=>{const good=async()=>({status:200,text:async()=>JSON.stringify({handDetected:false,label:null,text:null,confidence:null,error:null})});assert.equal((await request(server({fetch:good}),'POST','/api/interpret',JSON.stringify({image:'data:image/jpeg;base64,YQ=='}))).status,200);const malformed=async()=>({status:200,text:async()=>'{"secret":true}'});assert.equal((await request(server({fetch:malformed}),'POST','/api/interpret',JSON.stringify({image:'data:image/jpeg;base64,YQ=='}))).status,502);const huge=async()=>({status:200,text:async()=>'A'.repeat(MAX_UPSTREAM+1)});assert.equal((await request(server({fetch:huge}),'POST','/api/interpret',JSON.stringify({image:'data:image/jpeg;base64,YQ=='}))).status,502);});
test('maps upstream timeout to 502 and enforces loopback URL',async()=>{const pending=(_url,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Error('aborted'))));assert.equal((await request(server({fetch:pending,timeoutMs:2}),'POST','/api/interpret',JSON.stringify({image:'data:image/jpeg;base64,YQ=='}))).status,502);assert.throws(()=>loopbackUrl('https://example.com/interpret'),/loopback/);assert.throws(()=>server({inferenceUrl:'http://192.168.1.2:5001/interpret'}),/loopback/);});
test('sanitizes KSL provider and session metadata',()=>{const image='data:image/jpeg;base64,YQ==';assert.deepEqual(inferencePayload({image,provider:'ksl-experimental',sessionId:'meeting-1'}),{image,provider:'ksl-experimental',sessionId:'meeting-1'});assert.throws(()=>inferencePayload({image,provider:'ksl-experimental'}));assert.throws(()=>inferencePayload({image,provider:'other'}));});
