const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
global.chrome={action:{onClicked:{addListener(){}}},runtime:{onMessage:{addListener(){}}},scripting:{}};
const {isSupported,isValidMessage,requestInference,handleAction}=require('../background');
test('allows only Meet and Zoom HTTPS pages',()=>{assert.equal(isSupported('https://meet.google.com/abc-defg-hij'),true);assert.equal(isSupported('https://app.zoom.us/wc/123'),true);assert.equal(isSupported('https://example.com/'),false);assert.equal(isSupported('http://meet.google.com/'),false);});
test('validates inference messages',()=>{assert.equal(isValidMessage({type:'INTERPRET_FRAME',image:'data:image/jpeg;base64,YQ=='}),true);assert.equal(isValidMessage({type:'OTHER',image:'data:image/jpeg;base64,YQ=='}),false);assert.equal(isValidMessage({type:'INTERPRET_FRAME',image:'bad'}),false);});
test('validates KSL provider session metadata',()=>{const image='data:image/jpeg;base64,YQ==';assert.equal(isValidMessage({type:'INTERPRET_FRAME',image,provider:'ksl-experimental',sessionId:'meeting-1'}),true);assert.equal(isValidMessage({type:'INTERPRET_FRAME',image,provider:'ksl-experimental'}),false);assert.equal(isValidMessage({type:'INTERPRET_FRAME',image,provider:'other'}),false);});
test('times out inference cleanly',async()=>{const fetch=(_url,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(Error('abort'),{name:'AbortError'}))));assert.deepEqual(await requestInference({image:'data:image/jpeg;base64,YQ=='},fetch,2),{ok:false,error:'Inference request timed out'});});
test('packaged controller matches shared controller',()=>assert.equal(fs.readFileSync(path.resolve(__dirname,'../core.js'),'utf8'),fs.readFileSync(path.resolve(__dirname,'../../meeting-overlay/core.js'),'utf8')));
test('toolbar injects supported tabs and reports injection failure',async()=>{const calls=[];const api={action:{setBadgeText:async value=>calls.push(['badge',value.text]),setTitle:async value=>calls.push(['title',value.title])},scripting:{insertCSS:async()=>calls.push(['css']),executeScript:async()=>calls.push(['script'])}};await handleAction({id:1,url:'https://meet.google.com/a'},api);assert.deepEqual(calls.map(x=>x[0]),['badge','css','script']);api.scripting.executeScript=async()=>{throw Error('denied');};await handleAction({id:2,url:'https://app.zoom.us/wc/a'},api);assert.ok(calls.some(x=>x[0]==='title'&&/Could not/.test(x[1])));});
